name: gymapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  csv: ^6.0.0
  file_picker: ^11.0.2
  fl_chart: ^1.2.0
  flutter:
    sdk: flutter
  flutter_gemma: ^1.6.5
  flutter_gemma_litertlm: ^1.5.2
  flutter_local_notifications: ^19.5.0
  share_plus: ^12.0.2
  shared_preferences: ^2.5.5
  sqflite: ^2.4.2
  timezone: ^0.10.1
  wakelock_plus: ^1.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  sqflite_common_ffi: ^2.3.7+1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - esercizi2_en_fields_minified.json

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
